version: '3.3'

volumes:
  static_volume:
  media:
  pg_data_production:

services:

  frontend:
    image: relaxrazlom/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.10
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: relaxrazlom/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/staticfiles/
      - media:/var/html/media/
    depends_on:
      - backend

